basePath: /api
definitions:
  crud.Renew:
    properties:
      refresh_token:
        type: string
    type: object
  crud.SignInCredentials:
    properties:
      password:
        maxLength: 255
        type: string
      username:
        maxLength: 255
        type: string
    required:
    - password
    - username
    type: object
  crud.SignUpCredentials:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 255
        type: string
      username:
        maxLength: 255
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact:
    email: edgardanielgd123@gmail.com
    name: API Support
  description: Idealist project API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  version: "1.0"
paths:
  /v1/token/renew:
    post:
      consumes:
      - application/json
      description: Renew access token
      parameters:
      - description: Refresh Token Schema
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.Renew'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Renew access and refresh tokens
      tags:
      - Token
  /v1/token/verify:
    post:
      consumes:
      - application/json
      description: Get user identifier from JWT token
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user info
      tags:
      - Token
  /v1/user/sign/in:
    post:
      consumes:
      - application/json
      description: Log In user and return access and refresh token.
      parameters:
      - description: Log In Schema
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.SignInCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: User Sign In
      tags:
      - User
  /v1/user/sign/out:
    post:
      consumes:
      - application/json
      description: De-authorize user and delete refresh token from cache.
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: De-authorize user
      tags:
      - User
  /v1/user/sign/up:
    post:
      consumes:
      - application/json
      description: Create a new user given username, email and password
      parameters:
      - description: Sign Up Schema
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/crud.SignUpCredentials'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Create a new user
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
